export const districts = [{
  name: "Auburn",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Balmain",
  incumbent: "GRN",
  featured: true,
}, {
  name: "Bankstown",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Baulkham Hills",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Bega",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Blacktown",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Blue Mountains",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Cabramatta",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Camden",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Campbelltown",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Canterbury",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Castle Hill",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Coogee",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Cronulla",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Davidson",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Drummoyne",
  incumbent: "LNP",
  featured: true,
}, {
  name: "East Hills",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Epping",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Fairfield",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Goulburn",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Granville",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Hawkesbury",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Heathcote",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Heffron",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Holsworthy",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Hornsby",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Keira",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Kiama",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Kogarah",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Ku-ring-gai",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Lane Cove",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Lakemba",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Liverpool",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Londonderry",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Macquarie Fields",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Manly",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Maroubra",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Miranda",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Monaro",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Mount Druitt",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Mulgoa",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Newtown",
  incumbent: "GRN",
  featured: true,
}, {
  name: "North Sydney",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Oatley",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Parramatta",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Penrith",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Pittwater",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Prospect",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Riverstone",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Rockdale",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Ryde",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Seven Hills",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Shellharbour",
  incumbent: "ALP",
  featured: true,
}, {
  name: "South Coast",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Strathfield",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Summer Hill",
  incumbent: "ALP",
  featured: true,
}, {
  name: "Sydney",
  incumbent: "OTH",
  featured: true,
}, {
  name: "Vaucluse",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Wakehurst",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Willoughby",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Wollondilly",
  incumbent: "LNP",
  featured: true,
}, {
  name: "Wollongong",
  incumbent: "ALP",
  featured: true,
}];
