export const storageKey = "NSW_2019_1550966428001";

export const districts = [{
  name: "Albury",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Auburn",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Ballina",
  incumbent: "GRN",
  party: "",
  featured: true,
}, {
  name: "Balmain",
  incumbent: "GRN",
  party: "GRN",
  featured: false,
}, {
  name: "Bankstown",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Barwon",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Bathurst",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Baulkham Hills",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Bega",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Blacktown",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Blue Mountains",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Cabramatta",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Camden",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Campbelltown",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Canterbury",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Castle Hill",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Cessnock",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Charlestown",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Clarence",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Coffs Harbour",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Coogee",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Cootamundra",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Cronulla",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Davidson",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Drummoyne",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Dubbo",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "East Hills",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Epping",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Fairfield",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Gosford",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Goulburn",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Granville",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Hawkesbury",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Heathcote",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Heffron",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Holsworthy",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Hornsby",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Keira",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Kiama",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Kogarah",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Ku-ring-gai",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Lake Macquarie",
  incumbent: "OTH",
  party: "OTH",
  featured: false,
}, {
  name: "Lakemba",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Lane Cove",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Lismore",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Liverpool",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Londonderry",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Macquarie Fields",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Maitland",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Manly",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Maroubra",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Miranda",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Monaro",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Mount Druitt",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Mulgoa",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Murray",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Myall Lakes",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Newcastle",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Newtown",
  incumbent: "GRN",
  party: "GRN",
  featured: false,
}, {
  name: "North Shore",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Northern Tablelands",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Oatley",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Orange",
  incumbent: "OTH",
  party: "OTH",
  featured: false,
}, {
  name: "Oxley",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Parramatta",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Penrith",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Pittwater",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Port Macquarie",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Port Stephens",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Prospect",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Riverstone",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Rockdale",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Ryde",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Seven Hills",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Shellharbour",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "South Coast",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Strathfield",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Summer Hill",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Swansea",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Sydney",
  incumbent: "OTH",
  party: "OTH",
  featured: false,
}, {
  name: "Tamworth",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Terrigal",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "The Entrance",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Tweed",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Upper Hunter",
  incumbent: "LNP",
  party: "",
  featured: true,
}, {
  name: "Vaucluse",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Wagga Wagga",
  incumbent: "OTH",
  party: "OTH",
  featured: false,
}, {
  name: "Wakehurst",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Wallsend",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Willoughby",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Wollondilly",
  incumbent: "LNP",
  party: "LNP",
  featured: false,
}, {
  name: "Wollongong",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}, {
  name: "Wyong",
  incumbent: "ALP",
  party: "ALP",
  featured: false,
}];
